pub mod function_call;
pub mod function_definition;
pub mod if_condition;
pub mod infix;
pub mod prefix;
pub mod value;
pub mod value_function_call;
pub mod variable_assignment;
pub mod variable_definition;
